<?php

namespace App\Console\Commands;

use App\Models\Hospital;
use App\Models\User;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Str;
use Illuminate\Validation\Rules\Password;

class CreateHospitalAdmin extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'hospital:create-admin
        {hospital_id : The ID of the hospital to assign the admin to}
        {--name= : The full name of the administrator}
        {--email= : The email address of the administrator}
        {--phone= : The phone number of the administrator}
        {--password= : The password for the administrator (auto-generated if omitted)}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Create a hospital administrator for a given hospital';

    /**
     * Execute the console command.
     *
     * Creates a new User record with the `hospital_admin` role, linked
     * to the specified hospital. If optional fields (name, email, phone)
     * are omitted, the command runs interactively. When --password is
     * not provided, a random 16-character password is generated and
     * displayed to the operator.
     */
    public function handle(): int
    {
        $hospitalId = (int) $this->argument('hospital_id');

        // ── Validate hospital exists ─────────────────────────────────
        $hospital = Hospital::find($hospitalId);

        if (! $hospital) {
            $this->error("Hospital with ID #{$hospitalId} does not exist.");
            return self::FAILURE;
        }

        if (! $hospital->isActive()) {
            $this->warn('This hospital is not currently active. Admin will be created but may have limited access.');
        }

        // ── Collect or confirm fields ────────────────────────────────
        $name = $this->option('name') ?? $this->ask('Administrator name');
        $email = $this->option('email') ?? $this->ask('Administrator email');
        $phone = $this->option('phone') ?? $this->ask('Administrator phone number');
        $password = $this->option('password');

        if (empty($name)) {
            $this->error('Name is required.');
            return self::FAILURE;
        }

        if (empty($email) || ! filter_var($email, FILTER_VALIDATE_EMAIL)) {
            $this->error('A valid email address is required.');
            return self::FAILURE;
        }

        // ── Check for duplicate email ───────────────────────────────
        if (User::withTrashed()->where('email', $email)->exists()) {
            $this->error("A user with email \"{$email}\" already exists.");
            return self::FAILURE;
        }

        // ── Password handling ────────────────────────────────────────
        if (empty($password)) {
            $password = $this->secret('Enter password (leave blank to auto-generate)');
        }

        $autoGenerated = false;
        if (empty($password)) {
            $password = Str::random(16);
            $autoGenerated = true;
        }

        // Validate password strength
        $passwordRule = Password::min(8)->mixedCase()->numbers();

        if (! $passwordRule->passes(null, $password)) {
            $this->error(
                'Password must be at least 8 characters and contain at least '
                .'one uppercase letter, one lowercase letter, and one number.'
            );
            return self::FAILURE;
        }

        // ── Create user ──────────────────────────────────────────────
        try {
            DB::transaction(function () use ($hospital, $name, $email, $phone, $password) {
                User::create([
                    'hospital_id' => $hospital->id,
                    'name' => $name,
                    'email' => $email,
                    'phone' => $phone,
                    'password' => Hash::make($password),
                    'role' => 'hospital_admin',
                    'status' => 'active',
                    'email_verified_at' => now(),
                ]);
            });

            // ── Summary table ─────────────────────────────────────────
            $this->newLine();
            $this->info('Hospital administrator created successfully!');
            $this->newLine();

            $this->table(
                ['Field', 'Value'],
                [
                    ['Hospital', "{$hospital->name} (#{$hospital->id})"],
                    ['Name', $name],
                    ['Email', $email],
                    ['Phone', $phone ?? '—'],
                    ['Role', 'hospital_admin'],
                    ['Status', 'active'],
                ]
            );

            if ($autoGenerated) {
                $this->warn("Auto-generated password: {$password}");
                $this->warn('Make sure to save this password — it will not be shown again.');
            }

            Log::info('CreateHospitalAdmin command: Hospital admin created.', [
                'hospital_id' => $hospital->id,
                'hospital_name' => $hospital->name,
                'name' => $name,
                'email' => $email,
                'password_auto_generated' => $autoGenerated,
            ]);

            return self::SUCCESS;
        } catch (\Throwable $e) {
            $this->error("Failed to create hospital administrator: {$e->getMessage()}");
            Log::error('CreateHospitalAdmin command: Failed.', [
                'hospital_id' => $hospitalId,
                'error' => $e->getMessage(),
                'trace' => $e->getTraceAsString(),
            ]);

            return self::FAILURE;
        }
    }
}
